var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/generate-banner/route.js")
R.c("server/chunks/src_app_api_generate-banner_route_0jyv4me.js")
R.c("server/chunks/node_modules_next_dist_01k6gco._.js")
R.c("server/chunks/node_modules_@supabase_postgrest-js_dist_index_mjs_0uel2xe._.js")
R.c("server/chunks/node_modules_@supabase_auth-js_dist_module_00jw3pg._.js")
R.c("server/chunks/node_modules_0zhdfe~._.js")
R.c("server/chunks/[root-of-the-server]__0dr5gid._.js")
R.c("server/chunks/_next-internal_server_app_api_generate-banner_route_actions_05ld393.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/generate-banner/route.js [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/generate-banner/route.js [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
